config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'
  devise_for :users
  resources :characters
  # get '/characters' => 'characters#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  # has_and_belongs_to_many :items
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  belongs_to :location
  # has_one :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :characters
  # belongs_to :enemy
end

app/models/location.rb
class Location < ApplicationRecord
  has_one :enemy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :characters, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # before_action :authenticate_user!

  def index
    @characters = Character.all
    render :index
  end

  def new
    @character = Character.new
    render :new
  end

  def create
    @character = Character.new(character_params)
    @character[:user_id] = current_user.id
    if @character.save
      flash[:notice] = 'Character was successfully created'
      redirect_to characters_path
    else
      flash[:notice] = 'Character was not successfully created'
      render :new
    end
  end

  def show
    @character = Character.find(params[:id])
    @items = Item.all
    render :show
  end

  def edit
    @character = Character.find(params[:id])
    render :edit
  end

  def update
    @character = Character.find(params[:id])
    if @character.update
      flash[:notice] = 'Character was successfully updated'
      redirect_to character_path
    else
      flash[:notice] = 'Character was not successfully updated'
      redirect_to :edit
    end
  end

  def destroy
    Character.find(params[:id]).destroy
    flash[:notice] = 'Character was successfully deleted'
    redirect_to characters_path
  end

  private
  def character_params
    params.require(:character).permit(:name, :role, :health)
  end
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  # before_action :authenticate_user!

  def index
    @enemies = Enemy.all
    render :index
  end

  def new
    @enemy = Enemy.new
    render :new
  end

  def create
    @enemy = Enemy.new(enemy_params)
    if @enemy.save
      flash[:notice] = 'Enemy was successfully created'
      redirect enemies_path
    else
      flash[:notice] = 'Enemy was not successfully created'
      render :new
    end
  end

  def show
    @enemy = Enemy.find(params[:id])
    render :show
  end

  def edit
    @enemy = Enemy.find(params[:id])
    render :edit
  end

  def update
    @enemy = Enemy.find(params[:id])
    if @enemy.update
      flash[:notice] = 'Enemy was successfully updated'
      redirect enemy_path
    else
      flash[:notice] = 'Enemy was not successfully updated'
      redirect :edit
    end
  end

  def destroy
    Enemy.find(params[:id]).destroy
    flash[:notice] = 'Enemy was successfully deleted'
    redirect enemies_path
  end

  private
  def enemy_params
    params.require(:enemy).permit(:name, :bully, :health)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @items = Item.all
    render :index
  end

  def new
    @item = Item.new
    render :new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = 'Item was successfully created'
      redirect items_path
    else
      flash[:notice] = 'Item was not successfully created'
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    render :show
  end

  def edit
    @item = Item.find(params[:id])
    render :edit
  end

  def update
    @item = Item.find(params[:id])
    if @item.update
      flash[:notice] = 'Item was successfully updated'
      redirect item_path
    else
      flash[:notice] = 'Item was not successfully updated'
      redirect :edit
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:notice] = 'Item was successfully deleted'
    redirect items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :health_bonus)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @locations = Location.all
    render :index
  end

  def new
    @location = Location.new
    render :new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:notice] = 'Location was successfully created'
      redirect locations_path
    else
      flash[:notice] = 'Location was not successfully created'
      render :new
    end
  end

  def show
    @location = Location.find(params[:id])
    render :show
  end

  def edit
    @location = Location.find(params[:id])
    render :edit
  end

  def update
    @location = Location.find(params[:id])
    if @location.update
      flash[:notice] = 'Location was successfully updated'
      redirect location_path
    else
      flash[:notice] = 'Location was not successfully updated'
      redirect :edit
    end
  end

  def destroy
    Location.find(params[:id]).destroy
    flash[:notice] = 'Location was successfully deleted'
    redirect locations_path
  end

  private
  def location_params
    params.require(:location).permit(:name, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.erb
<h1>Characters</h1>

<% if @characters.any? %>
  <ul>
    <% @characters.each do |character| %>
      <li><%= link_to character.name, character_path(character) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no characters yet.</p>
<% end %>

<p><%= link_to "Create new Character", new_character_path %></p>

app/views/characters/new.html.erb
<%= form_for @character do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :role %>
  <%= f.text_field :role %>
  <%= f.label :health %>
  <%= f.text_field :health %>
  <%= f.submit %>
<% end %>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>
<h2>HP:</h2><p><%= @character.health %></p>

<h2>Items</h2>
<% if @character.items.any? %>
  <ul>
    <% @character.items.each do |item| %>
      <li><%= link_to item.item_name, item_path(item) %></li>
    <% end %>
  </ul>
<% else %>
  <p>You character has no items yet.</p>
<% end %>


<p><%= link_to "Edit", edit_character_path(@character) %></p>
<p><%= link_to "Delete", character_path(@character), :data =>
  {
    :confirm => "You sure?",
    :method => "delete"
  } %></p>

<p><%= link_to "Return to characters", characters_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground Fights</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Playground</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/characters">Characters <span class="sr-only">(current)</span></a></li>
              <li><a href="/items">Items</a></li>
              <li><a href="/enemies">Enemies</a></li>
              <li><a href="/locations">Locations</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><a href="/users/edit"><span class="glyphicon glyphicon-update"></span> Update Account</a></li>
                <li><a href="/users/sign_out" data-method="delete"><%= current_user.email %> <span class="glyphicon glyphicon-log-out"></span></a></li>
              <% else %>
                <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

      <%= flash[:notice] %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Playground Prison Rules</h1>